theme: jekyll-theme-minimal
title: Gabriel Pelayo's super cool homepage
description: Bookmark this to see all the awesome stuff I do!
> With great power comes great responsibilites
- The best super heros uncle
![ picture of spiderman being cool.](https://www.pngitem.com/middle/hmTTowx_collection-of-free-drawing-spiderman-cartoon-download-spider/#)
